# Generated by Django 4.1.1 on 2022-09-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocatorcalc',
            name='deliveryZonesShop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='geoLocator.deliveryzonesshop'),
        ),
    ]
