# Generated by Django 4.1.1 on 2022-09-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocator', '0003_alter_geolocatorcalc_deliveryzonesshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocatorcalc',
            name='deliveryZonesShop',
        ),
        migrations.AddField(
            model_name='geolocatorcalc',
            name='deliveryZonesShop',
            field=models.ManyToManyField(blank=True, null=True, to='geoLocator.deliveryzonesshop'),
        ),
    ]
