# Generated by Django 4.1.1 on 2022-09-21 02:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocator', '0006_deliveryzoneshop_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressclient',
            name='point_client',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5880, verbose_name='Endereço Cliente'),
        ),
    ]
