# Generated by Django 4.1.1 on 2022-09-21 02:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocator', '0007_addressclient_point_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressclient',
            name='point_client',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=5880, verbose_name='Endereço Cliente'),
        ),
    ]
